version: '2'

services:
  
  ftpclient01:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: ftpclient01
    container_name: ftpclient01
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 10.28.1.101
    
  ftpserver:
    image: joaniznardo/ubuntum7ftp1
    privileged: true
    mem_limit: 100m
    hostname: ftpserver
    container_name: ftpserver
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 10.28.1.100

  filezilla:
    container_name: filezilla
    ports:
      - '5800:5800'
        #    volumes:
        #      - './filezilla:/config:rw'
        #      - '$HOME:/storage:rw'
    image: jlesage/filezilla
    networks:
      x1:
        ipv4_address: 10.28.1.102


networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 10.28.0.0/16
          ip_range: 10.28.1.0/30
          gateway: 10.28.1.1
          aux_addresses:
            host1: 10.28.1.2
            host2: 10.28.1.3
